### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by caroso1222** [caroso1222/amazon-autocomplete#13]
There seems to be a problem with the demo because of the latest SSL certificate addition: https://www.carlosroso.com/amazon-autocomplete/. The api endpoint call needs to be changed to https.

**Comment by geek92sunny** [comment]
The URL: https://www.carlosroso.com/amazon-autocomplete is not working

**Comment by caroso1222** [comment]
This issue has been fixed on 1.0.2. Closing.
