### ISSUE TITLE
Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by MichaelRise** [caroso1222/amazon-autocomplete#7]
Hey,

I can't use this plugin.
When I use advanced settings I have error - Cannot read property 'parentNode' of undefined - [https://jsfiddle.net/6c029v1k/](https://jsfiddle.net/6c029v1k/)
When I use simple method I can't click - [https://jsfiddle.net/aeg073ew/1/](https://jsfiddle.net/aeg073ew/1/)

Please help - what is wrong ?

Thanks
Michael

**Comment by caroso1222** [comment]
Gonna take a look at it. What do you mean by this?

> When I use simple method I can't click

I clicked into the second link and the plugin is working good. Would you please elaborate? I'll look into the problem `Cannot read property 'parentNode' of undefined` and get back to you.
